# Generated by Django 3.2.18 on 2023-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230307_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(help_text='Обязательно для заполнения', max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
